kimuray/nomini_reserve

app/controllers/admin/shops_controller.rb
app/models/reservation_category.rb
app/models/shop.rb
app/models/shop_reservation.rb
app/views/admin/shops/_form.html.erb
app/views/admin/shops/show.html.erb
db/migrate/20170909050927_create_shop_reservations.rb
db/schema.rb
spec/models/shop_reservation_spec.rb
spec/support/factories/shop_reservations.rb

店舗と予約カテゴリーの中間テーブルを作成しました。このテーブルで価格も管理する想定です。

店舗予約カテゴリ追加

---

app/controllers/admin/enquete_items_controller.rb
app/controllers/enquetes_controller.rb
app/models/enquete.rb
app/models/enquete_answer.rb
app/models/enquete_item.rb
app/models/enquete_selection.rb
app/models/reservation.rb
app/views/admin/enquete_items/_form.html.erb
app/views/admin/enquete_items/show.html.erb
app/views/enquetes/_enquete_item.html.erb
app/views/enquetes/new.html.erb
config/locales/model.ja.yml
config/routes.rb
db/migrate/20170910154659_create_enquete_selections.rb
db/schema.rb
spec/controllers/enquetes_controller_spec.rb
spec/models/enquete_selection_spec.rb
spec/support/factories/enquete_selections.rb

件名の通りアンケート機能を作成する
* アンケートルーティング、画面の土台を作成
* アンケート送信処理の作成
* 管理画面上でアンケートを閲覧できるようにする

アンケート機能の作成

---

app/assets/stylesheets/custom.scss
app/views/devise/registrations/new.html.erb
app/views/devise/sessions/new.html.erb
app/views/layouts/_footer.html.erb
app/views/layouts/_header.html.erb
app/views/layouts/_recommend.html.erb
app/views/layouts/application.html.erb
app/views/reservations/index.html.erb
app/views/shops/index.html.erb
app/views/shops/show.html.erb

店舗周りのデザインの作成とサインイン/サインアップ/マイページのレスポンシブ対応
- 店舗一覧画面デザイン
- 店舗詳細画面デザイン
- マイページレスポンシブ対応
- サインイン画面レスポンシブ対応
- サインアップ画面レスポンシブ対応
- ヘッダー/フッターレスポンシブ対応

店舗周りのデザイン&レスポンシブ対応

---

app/controllers/application_controller.rb
app/controllers/bank_accounts_controller.rb
app/models/bank_account.rb
app/models/user.rb
app/views/bank_accounts/edit.html.erb
app/views/bank_accounts/new.html.erb
app/views/devise/registrations/edit.html.erb
app/views/devise/registrations/new.html.erb
config/locales/model.ja.yml
config/routes.rb
db/migrate/20170827143905_devise_create_users.rb
db/migrate/20171008042749_create_bank_accounts.rb
db/schema.rb
spec/controllers/bank_accounts_controller_spec.rb
spec/models/bank_account_spec.rb
spec/support/factories/bank_accounts.rb

ユーザー登録画面の軽量化、管理の効率化のためにユーザーモデルから口座情報を分離
- DB設計変更
- ユーザー登録修正
- ユーザー更新修正
- 口座情報CRUD作成

ユーザー情報と口座情報を分離&口座登録フロー

---

config/environments/production.rb

本番環境のメーラー設定

---

Gemfile
Gemfile.lock
app/uploaders/shop_image_uploader.rb
config/initializers/carrierwave.rb

画像を外部ストレージに保存するためfogを導入

---

app/models/user.rb
app/views/devise/registrations/new.html.erb
app/views/layouts/_header.html.erb

- 新規会員登録時の入力項目が多く、新規ユーザーの障壁となりかねないため、入力項目を削減

新規会員登録時の入力項目削減

---

app/controllers/shop_page/reservations_controller.rb
app/controllers/shop_page_controller.rb
app/controllers/shops/sessions_controller.rb
app/controllers/shops_controller.rb
app/views/layouts/shop_page/_header.html.erb
app/views/layouts/shop_page/application.html.erb
app/views/shop_page/reservations/index.html.erb
config/routes.rb
spec/controllers/shop_page/reservations_controller_spec.rb

店舗側の操作を柔軟に行うために名前空間を作成
- 店舗ページ用ルーティング作成
- 店舗ページ用コントローラー/レウアウト作成

店舗向けページの作成

---

app/controllers/exchanges_controller.rb
app/models/exchange.rb

ポイント換金申請時に口座情報を取得を行わないように対応

---

Gemfile
Gemfile.lock
app/helpers/application_helper.rb
app/views/admin/shops/show.html.erb
app/views/shops/show.html.erb

#102 
マークダウンパーサーredcarpetを導入して店舗概要をマークダウンで記載できるように修正

店舗概要をマークダウンで記載できるように修正

---

app/assets/stylesheets/custom.scss
app/helpers/credit_card_helper.rb
app/views/reservation_payments/show.html.erb
app/views/shop_page/payments/new.html.erb

- 決済画面(カード入力画面)のデザイン修正
- 有効期限のセレクトボックス化
- レイアウト調整
- レスポンシブ対応

決済画面のデザイン修正

---

app/assets/stylesheets/custom.scss
app/views/subscriptions/new.html.erb

定期課金画面のデザイン修正

---

app/controllers/admin/subscriptions_controller.rb
app/controllers/admin/users_controller.rb
app/controllers/subscriptions_controller.rb
app/models/subscription.rb
app/views/admin/subscriptions/_form.html.erb
app/views/admin/subscriptions/index.html.erb
app/views/admin/subscriptions/show.html.erb
app/views/admin/users/_form.html.erb
app/views/admin/users/show.html.erb
config/locales/model.ja.yml
db/migrate/20171209030855_remove_payjp_token_to_subscriptions.rb
db/migrate/20171209035338_add_payment_on_to_subscription.rb
db/schema.rb

定期課金の20000円利用時の課金免除機能を作成するための下準備

定期課金周りの設計修正の準備

---

app/assets/stylesheets/custom.scss
app/views/devise/registrations/new.html.erb

新規登録画面デザイン変更

---

app/models/reservation_payment.rb
lib/batches/force_payment_batch.rb

強制決済の処理の不具合を修正

---

app/assets/javascripts/common.js
app/assets/stylesheets/custom.scss
app/views/shops/show.html.erb

スマートフォンでアクセスした際は電話番号をタップしたら電話を発信できるように修正
PCでアクセスした際は電話番号がリンクにならないようにjsで制御

電話番号リンクを有効化

---

app/assets/stylesheets/custom.scss
app/views/shops/show.html.erb

- 画像サイズの縦横比の調整
- アップロード画像に縦横比が極端な場合は黒背景使用

店舗詳細画像縦横比調整

---

app/controllers/admin/shops_controller.rb
app/controllers/shop_page/reservations_controller.rb
app/models/reservation.rb
app/models/reservation_payment.rb
app/views/admin/shared/_header.html.erb
app/views/mailers/shared/_reservation_content.html.erb
app/views/mailers/shared/_reservation_content_for_web.html.erb
app/views/reservations/confirm.html.erb
app/views/shop_page/reservations/confirm.html.erb
app/views/shop_page/reservations/new.html.erb

以下を対応
* 決済料金は税抜き価格で決済を行わせる
* 管理画面で店舗情報を入力する際にパスワードの入力を求めないようにする
* コース利用時に幹事分を引くように修正
ついでに対応
* 定期課金登録していないユーザーを電話番号検索に引っ掛けないように
* 店舗の予約画面でもアラカルトを選択できるように

error_reports対応

---

app/controllers/admin/shops_controller.rb
app/controllers/concerns/access_checkable.rb
app/controllers/shop_page/payments_controller.rb
app/controllers/shop_page/reservations_controller.rb
app/controllers/shop_page_controller.rb
app/controllers/shops_controller.rb
app/views/admin/shops/_form.html.erb
app/views/admin/shops/index.html.erb
app/views/admin/shops/show.html.erb
app/views/shop_page/request_agreement.html.erb
config/locales/model.ja.yml
config/routes.rb
db/migrate/20171216150254_add_is_agree_to_shops.rb
db/schema.rb

#141
店舗がログインしてアクセスする画面に遷移する際に利用規約の同意チェックを行うように修正
↓こんな感じ

店舗に利用規約同意させる機能を作成

---

app/assets/stylesheets/custom.scss
app/views/layouts/_header.html.erb
app/views/reservations/confirm.html.erb
app/views/shops/show.html.erb

モバイルメニュー&デザイン微調整

---

app/assets/stylesheets/custom.scss
app/views/shops/show.html.erb

- 店舗詳細のレイアウト修正
- h1タグが使用された際のデザイン修正

店舗詳細のレイアウト修正

---

app/controllers/concerns/access_checkable.rb
app/controllers/exchanges_controller.rb
app/controllers/reservation_payments_controller.rb
app/controllers/reservations_controller.rb
app/controllers/shop_page/payments_controller.rb
app/controllers/shop_page/reservations_controller.rb
app/views/reservation_payments/show.html.erb
app/views/shop_page/payments/new.html.erb

show, edit, updateなどfind(params[:id])しているような箇所をチェックするようにした

アクセス制御周りを作成

---

app/assets/stylesheets/custom.scss
app/views/shops/show.html.erb

- 店名の黒背景に指摘を受けたため削除
- フォントの指定を追加

デザイン修正&フォント変更

---

app/views/layouts/application.html.erb

- マイページに表示されるおすすめ店舗一覧をカード登録していないユーザーには表示しないように修正

カード登録していないユーザーにはpickupを表示しない

---

app/views/layouts/application.html.erb

- 定期課金していないユーザーに対してマイページのpickupを非表示にする対応において、条件設定を誤っていたため、対応

pickup条件設定修正

---

app/views/layouts/_facebook_page.html.erb
app/views/layouts/application.html.erb

マイページレイアウトの微調整

---

app/assets/stylesheets/custom.scss
app/views/shops/index.html.erb

Design adjust 11

---

app/assets/stylesheets/custom.scss
app/views/devise/registrations/new.html.erb
app/views/devise/sessions/new.html.erb
app/views/subscriptions/new.html.erb

- モバイルレイアウト変更
- ログイン画面
- 新規登録画面
- 本登録画面

モバイルレイアウト調整

---

app/assets/stylesheets/custom.scss
app/views/layouts/_mobile_fixed_menu.html.erb
app/views/layouts/_mobile_nav.html.erb
app/views/layouts/application.html.erb

- モバイル用固定メニュー作成
- モバイルメニューにログアウト追加

モバイル用固定メニュー作成

---

app/views/subscriptions/new.html.erb

件名の対応
バリデーションメッセージと同様に表示するように修正

カード情報の入力ミス時にエラーメッセージを表示するように修正

---

app/controllers/reservation_payments_controller.rb
app/controllers/shop_page/payments_controller.rb
app/controllers/shop_page/reservations_controller.rb
app/models/reservation.rb
app/models/reservation_payment.rb

* アラカルトのみポイントが付与されるように修正
* 支払い情報作成メールのリンクに飛んだ際ログインしていなければログイン画面に遷移するように修正
* 店舗ページから支払い情報作成画面に遷移できるリンクの作成

コース予約の支払いに関してはポイントを付与しないように修正

---

app/views/layouts/_mobile_nav.html.erb
app/views/layouts/_pc_nav.html.erb

利用方法リンクを追加

---

app/assets/stylesheets/custom.scss
app/views/layouts/_header.html.erb

- ヘッダーコンテンツをコンテナに納める
- ロゴ左寄せ
- ヘッダーの高さ修正

ロゴ位置修正&ヘッダーの高さ修正

---

app/views/mailers/shared/_reservation_content_for_web.html.erb
app/views/reservations/confirm.html.erb
app/views/shop_page/reservations/confirm.html.erb

メール文面の時間が00:00になってしまう不具合修正

---

app/assets/stylesheets/custom.scss
app/controllers/subscriptions_controller.rb
app/controllers/users_controller.rb
app/models/user.rb
app/views/users/new.html.erb
config/routes.rb

- 新規会員登録と同時に定期課金データを保存する画面を作成。
- http://localhost:3000/user/member/new
- devise非依存の形で再実装
- javascriptのリファクタは次の機会に・・・

一括本登録画面を作成

---

app/assets/stylesheets/custom.scss
app/views/users/new.html.erb

Design adjust 12

---

Gemfile
Gemfile.lock
app/assets/stylesheets/custom.scss
app/controllers/admin/shops_controller.rb
app/models/shop.rb
app/views/admin/shops/_form.html.erb
app/views/shops/show.html.erb
config/locales/model.ja.yml
db/migrate/20180224150007_add_place_to_shops.rb
db/migrate/20180225143338_add_is_display_map_to_shops.rb
db/schema.rb

住所から緯度軽度を求めるgemとGoogleMapAPIを用いて店舗詳細にGoogleMapを表示
要環境変数設定

店舗詳細にGoogleMap表示

---

app/views/shops/show.html.erb

環境変数の設定ミス修正

---

app/controllers/users/confirmations_controller.rb
app/views/layouts/application.html.erb
app/views/statics/thanks.html.erb
config/routes.rb

コンバージョンを測定するためにコンバージョンタグを設置した
* thanksページを作成
* メール認証後にthanksページに遷移するようにした
* thanksページにコンバージョンタグを設置

コンバージョンタグの設置
